### ISSUE TITLE
購入商品名で絞り込んで配信すると同一会員に複数回メール送信してしまう

### ISSUE THREAD

**Issue by dk-umebius** [EC-CUBE/mail-magazine-plugin#100]
コミュニティより（おそらくこのissueの問題だと思われる)
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=24760&forum=1&post_id=100320#forumpost100320

概要
"購入商品名"で会員を検索してメルマガ配信すると同一会員に対して該当するOrderItemの明細の数だけメールを送信してしまう。

環境
EC-CUBE4.0.5
メールマガジンプラグイン 4.0.2

再現手順
1.  同一会員が同一Productを複数回購入する
2. 配信メニューから1の商品名を購入商品名で検索してリストを作成（この時点では複数回購入していても同一会員が複数回表示されるわけではないため気づきにくい)
3. 配信手順を進める
4. 配信を実行すると同一会員に複数回メール送信される(該当するOrderItemの明細の数だけ) 

![スクリーンショット 0032-10-15 21 53 13](https://user-images.githubusercontent.com/4304985/96129115-301db700-0f31-11eb-8582-7067537897e5.png)
![スクリーンショット 0032-10-15 21 53 43](https://user-images.githubusercontent.com/4304985/96129124-3318a780-0f31-11eb-9c7a-99286a2e5ff2.png)
![スクリーンショット 0032-10-15 21 54 00](https://user-images.githubusercontent.com/4304985/96129128-33b13e00-0f31-11eb-93dd-e317d45546e4.png)

**Comment by okazy** [comment]
#101 にて修正されましたのでクローズします。
本修正は 4.0.3 のバージョンに含まれる予定です。
ご報告、ご対応ありがとうございました。
