### ISSUE TITLE
配信履歴で表示件数を変更した場合の表示を修正

### ISSUE THREAD

**Issue by kanako-kina** [EC-CUBE/mail-magazine-plugin#123]
配信履歴のページを開き、表示件数を50件以外に変更すると会員一覧に遷移するため
表示件数に応じて履歴が表示されるよう修正が必要。

URL直打ちでpage_noを入力した場合は問題なく表示される。

**Comment by Yangsin** [comment]
https://github.com/EC-CUBE/mail-magazine-plugin/pull/122 で解決するかも？

**Comment by chihiro-adachi** [comment]
#122 で対応
