### ISSUE TITLE
HTMLメルマガが送信できない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/mail-magazine-plugin#13]
## 現象

http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=17642&forum=15&post_id=76576#forumpost76576
## 対応案
1. テンプレート登録・編集時に、テキストメール/HTMLメールの設定項目を追加する
2. メール配信時に、1の設定内容を確認し、content-typeを切り替える

**Comment by lqdung-lockon** [comment]
#15

**Comment by ryo-endo** [comment]
1.0.0でmultipart/alternative形式のメールマガジン配信に対応。
