### ISSUE TITLE
誕生月の検索条件が無効

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/mail-magazine-plugin#19]
[フォーラム](http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=17753&forum=9&post_id=76967#forumpost76967)より

https://github.com/EC-CUBE/mail-magazine-plugin/blob/42425206d58071fd7dd56025236fe6e5deffbf04/Repository/MailMagazineCustomerRepository.php#L204

**Comment by ryo-endo** [comment]
ご報告ありがとうございます。

**Comment by ryo-endo** [comment]
v.1.0.0で対応済み。
