### ISSUE TITLE
会員管理/会員登録・編集で、バリデーションが通らない場合にシステムエラーなど

### ISSUE THREAD

**Issue by goohib** [EC-CUBE/mail-magazine-plugin#22]
会員管理/会員登録・編集で、会員登録時にバリデーションが通らない場合に下記のような現象となります
#### 新規会員の場合

システムエラーとなります
#### 既存会員の場合

バリデーションが通らない際にも、誤った値のまま会員情報が保存され、メールマガジン送付についての選択状態も強制的に保存されます。

**Comment by ryo-endo** [comment]
ご報告ありがとうございます。
PR含めて早めに確認させていただきます。

**Comment by goohib** [comment]
PR #23 テストコードが違っていたので修正しました

**Comment by ryo-endo** [comment]
v.1.0.0で取り込み済み。
