### ISSUE TITLE
YamlのEntity設定ファイルの中にテーブル名が間違えてます

### ISSUE THREAD

**Issue by trebla-on** [EC-CUBE/mail-magazine-plugin#31]
ec-cube 3.0.12
プラグイン：MailMagazine 0.0.3

問題：YamlのEntity設定ファイルの中にテーブル名が間違えてます
ファイル：app/Plugin/MailMagazine/Resource/doctrine/Plugin.MailMagazine.Entity.MailMagazineCustomer.dcm.yml
行目：3
    table: dtb_customer

**Comment by ryo-endo** [comment]
v.1.0.0で対応済み。
