### ISSUE TITLE
会員種別など詳細な検索条件を指定して検索したときに検索フォームが閉じたまま

### ISSUE THREAD

**Issue by kiy0taka** [EC-CUBE/mail-magazine-plugin#32]
会員種別などの詳細な検索条件を指定するときは「+」をクリックして検索フォームを開いて検索するが、検索結果が表示されたときには検索フォームが閉じたままになっている。

商品マスタや会員マスタなどの検索と同様に、詳細な検索条件を指定して検索した場合は、検索フォームを開いたままにしておいたほうが良い。

**Comment by ryo-endo** [comment]
v.1.0.0で対応済み。
