### ISSUE TITLE
誕生月の「1月」の検索が機能しない

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/mail-magazine-plugin#49]
開発コミュニティより

誕生月で検索をかけた場合、「1月」を選択した場合のみ全件表示となってしまう。（他の月を選択した場合は正常に稼働している）

http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=18584&forum=9&post_id=80024#forumpost80024

以下の箇所で、emptyで判定しているが、「1月」を選択した場合、「0」がPOSTされるため処理を通らない。
https://github.com/EC-CUBE/mail-magazine-plugin/blob/master/Repository/MailMagazineCustomerRepository.php#L108

**Comment by okazy** [comment]
1.0.3にて修正されましたのでクローズします。
