### ISSUE TITLE
配信履歴ページでページネーションおよび表示件数変更が動かない

### ISSUE THREAD

**Issue by 3tiles** [EC-CUBE/mail-magazine-plugin#73]
開発コミュニティより

4.0系の配信履歴ページにて、ページネーションをクリック、および表示件数のセレクトボックスにて件数変更すると会員一覧ページに遷移してしまう。

https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22215&forum=1

**Comment by okazy** [comment]
ありがとうございます。プルリクが取り込まれましたのでクローズします。
