### ISSUE TITLE
配信履歴を削除する際、モーダルのラベルが正しく表示されていない

### ISSUE THREAD

**Issue by junpeko5** [EC-CUBE/mail-magazine-plugin#79]
## 概要(Overview)

配信履歴画面の削除リンクを押下時、削除確認のモーダルが開くが、その際表示されるモーダルの削除ボタン、キャンセルボタンの表示が正しく表示されない。

![2019-09-02_15h41_30](https://user-images.githubusercontent.com/26207848/64095025-9e88cf80-cd98-11e9-9db3-b5f80aecffdf.png)

## 期待する内容(Expect)  or 要望 (Requirement)

ボタンのラベル表示が正しく表示されること

## 再現手順(Procedure)

配信履歴画面で削除リンクを押下する

### 環境 (environment)
+ EC-CUBE: 4.0.2
+ PHP: 7.x.x
+ DB:
  - PostgreSQL x.x.x 
  - MySQL x.x.x

4.0.2、4.0.3環境ともに同じ挙動となりました。

**Comment by okazy** [comment]
こちらで修正されましたのでクローズします。
https://github.com/EC-CUBE/mail-magazine-plugin/pull/84
