### ISSUE TITLE
仮会員を対象外にしても送信されてしまう

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/mail-magazine-plugin#82]
開発コミュニティより。
配信→詳細検索→会員種別　で仮会員のチェックをはずしたのに送信すると仮会員にも送信される。

要再現確認

https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22714&forum=16&post_id=94442#forumpost94442

**Comment by okazy** [comment]
#90 で修正されましたのでクローズします。
