### ISSUE TITLE
配信履歴の誕生月が1ヶ月ずれる

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/mail-magazine-plugin#83]
開発コミュニティより

誕生月を11月と選択して配信すると配信履歴には12と入る。実際に配信される対象者は11月だったので配信履歴の表示が1ずれる。
#49 にも関連

https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22714&forum=16&post_id=94442#forumpost94442

**Comment by ryo-endo** [comment]
修正取り込まれました。報告ありがとうございました
