### ISSUE TITLE
Entityのtypeが、datetimetzではなくdatetimeになっている

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/mail-magazine-plugin#85]
Entityのtypeが、datetimetzではなくdatetimeになっています。
EC-CUBE本体に合わせて `datetimetz ` にしておくほうが良い。

### 影響
EC-CUBE本体で、DBに保存するときにはUTCへの変換を行っており、実害はないかもしれません。

### 該当コード
https://github.com/EC-CUBE/mail-magazine-plugin/blob/4.0/Entity/MailMagazineSendHistory.php#L88
https://github.com/EC-CUBE/mail-magazine-plugin/blob/4.0/Entity/MailMagazineSendHistory.php#L95

他にもあるかも。

**Comment by chihiro-adachi** [comment]
#105 で修正
