### ISSUE TITLE
会員登録の入力画面で入力エラーになると、ラジオボタンが消える

### ISSUE THREAD

**Issue by sw-satoshi-nakano** [EC-CUBE/mail-magazine-plugin#86]
![会員登録(入力ページ)](https://user-images.githubusercontent.com/22627978/67929519-dd080280-fc00-11e9-9995-a68e74548ed6.png)

https://github.com/EC-CUBE/mail-magazine-plugin/blob/1dae04dcb47020c7696dc743feb1bed6e30762c3/Resource/template/entry_add_mailmaga.twig#L32-L42

エラーで入力画面に戻ってきた時の考慮がされていない

**Comment by okazy** [comment]
修正が取り込まれたのでクローズします。
